#!/bin/bash



if test "$1" != "1"; then 


if [ "1" = "1" ]; then 
    ppddir=/usr/share/ppd 
    # Remove link to PPD file directory 
    [ -d /opt/OpenPrinting-Ricoh/ppds ] && rmdir /opt/OpenPrinting-Ricoh/ppds 2> /dev/null 
    [ -h $ppddir/OpenPrinting-Ricoh ] && [ ! -e $ppddir/OpenPrinting-Ricoh ] && \
      	 rm -f $ppddir/OpenPrinting-Ricoh 
    [ -d $ppddir/OpenPrinting-Ricoh ] && [ -h $ppddir/OpenPrinting-Ricoh/ppds ] && \
         [ ! -e $ppddir/OpenPrinting-Ricoh/ppds ] && rm -f $ppddir/OpenPrinting-Ricoh/ppds 
fi 



if [ -x /etc/init.d/cups ]; then 
   cups="cups" 
else 
    if [ -x /etc/init.d/cupsys ]; then 
	cups="cupsys" 
    fi 
fi 
if [ ! -z "$cups" ]; then 
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then 
	invoke-rc.d $cups restart 2>/dev/null || true 
    else 
	/etc/init.d/$cups restart 2>/dev/null || true 
    fi 
fi 


fi